# Generated by Django 5.2 on 2025-05-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_usercourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='study_year',
            field=models.CharField(choices=[('1', 'First Year'), ('2', 'Second Year'), ('3', 'Third Year')], default='1', max_length=20),
        ),
    ]
