# Generated by Django 5.2 on 2025-05-04 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_course_study_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='study_year',
        ),
        migrations.RemoveField(
            model_name='student',
            name='study_year',
        ),
    ]
