# Generated by Django 5.2 on 2025-05-05 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_remove_course_study_year_remove_student_study_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='eligible_years',
            field=models.CharField(default='1,2,3', help_text='Comma-separated years that can take this course (e.g., "1,2,3")', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='year_of_study',
            field=models.CharField(choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year')], default='1', max_length=1),
        ),
    ]
