# Generated by Django 5.2 on 2025-05-05 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_course_eligible_years_student_year_of_study'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='eligible_years',
        ),
        migrations.RemoveField(
            model_name='student',
            name='year_of_study',
        ),
    ]
